services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wizlearn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: shanawar07/wizlearn-backend:latest
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/wizlearn
      PORT: 3000
      JWT_SECRET: "your-secret-key-here"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_SSL: 'false'
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: shanawar07/wizlearn-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
